name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Only read permission is needed for checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # GitHub Secret for Access Key ID
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # GitHub Secret for Secret Access Key
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync files to S3 bucket
        run: |
          aws s3 sync . s3://${{ env.S3_BUCKET_NAME }} \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "node_modules/*" # Add any other files/folders to exclude

      - name: Create CloudFront invalidation
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*" # Invalidate all paths. Use specific paths for more granular invalidation.
